<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AppExpose</AssemblyName>
    <RootNamespace>PlebTools.AppExpose</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AppExpose.Tests\**\*.cs" />
    <EmbeddedResource Remove="AppExpose.Tests\**\*" />
    <None Remove="AppExpose.Tests\**\*" />
  </ItemGroup>
</Project>
